-- Genre Additions for the OpenDB Open Media Lending Database.
-- Created by Michael Plugge based on the available Genres in Winamp
-- and commonly seen in the FreeDB music database.

INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'acapella', 'Acapella', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'acid', 'Acid', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'acidjazz', 'Acid Jazz', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'acidpunk', 'Acid Punk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'acoustic', 'Acoustic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'alternative', 'Alternative', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'alternrock', 'AlternRock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'ambient', 'Ambient', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'anime', 'Anime', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'avantgarde', 'Avantgarde', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'ballad', 'Ballad', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'bass', 'Bass', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'beat', 'Beat', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'bebop', 'Bebop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'bigband', 'Big Band', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'blackmetal', 'Black Metal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'bluegrass', 'Bluegrass', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'bootybass', 'Booty Bass', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'britpop', 'BritPop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'cabaret', 'Cabaret', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'celtic', 'Celtic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'chambermusic', 'Chamber Music', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'chanson', 'Chanson', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'chorus', 'Chorus', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'christianganstarap', 'Christian Gangsta Rap', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'christianrap', 'Christian Rap', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'christianrock', 'Christian Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'classicrock', 'Classic Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'club', 'Club', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'club-house', 'Club-House', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'comedy', 'Comedy', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'contemporarychristian', 'Contemporary Christian', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'crossover', 'Crossover', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'cult', 'Cult', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'dance', 'Dance', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'dancehall', 'Dance Hall', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'darkwave', 'Darkwave', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'deathmetal', 'Death Metal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'disco', 'Disco', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'dream', 'Dream', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'drumbass', 'Drum & Bass', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'drumsolo', 'Drum Solo', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'duet', 'Duet', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'easylistening', 'Easy Listening', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'electronic', 'Electronic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'ethnic', 'Ethnic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'eurodance', 'Eurodance', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'eurohouse', 'Euro-House', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'eurotechno', 'Euro-Techno', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'fastfusion', 'Fast Fusion', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'folklore', 'Folklore', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'folkrock', 'Folk-Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'freestyle', 'Freestyle', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'funk', 'Funk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'fusion', 'Fusion', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'game', 'Game', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'gangsta', 'Gangsta', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'goa', 'Goa', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'gospel', 'Gospel', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'gothic', 'Gothic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'gothicrock', 'Gothic Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'grunge', 'Grunge', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'hardcore', 'Hardcore', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'hardrock', 'Hard Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'heavymetal', 'Heavy Metal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'hiphop', 'Hip-Hop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'house', 'House', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'humour', 'Humour', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'indie', 'Indie', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'industrial', 'Industrial', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'instrumental', 'Instrumental', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'instrumentalpop', 'Instrumental Pop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'instrumentalrock', 'Instrumental Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'jazzfunk', 'Jazz+Funk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'jpop', 'JPop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'jungle', 'Jungle', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'latin', 'Latin', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'lofi', 'Lo-Fi', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'meditative', 'Meditative', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'merengue', 'Merengue', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'metal', 'Metal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'musical', 'Musical', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'nationalfolk', 'National Folk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'nativeamerican', 'Native American', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'negerpunk', 'Negerpunk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'newwave', 'New Wave', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'noise', 'Noise', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'oldies', 'Oldies', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'opera', 'Opera', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'other', 'Other', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'polka', 'Polka', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'polskpunk', 'Polsk Punk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'popfolk', 'Pop-Folk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'popfunk', 'Pop/Funk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'porngroove', 'Porn Groove', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'powerballad', 'Power Ballad', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'pranks', 'Pranks', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'primus', 'Primus', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'progressiverock', 'Progressive Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'psychedelic', 'Psychedelic', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'psychedelicrock', 'Psychedelic Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'punk', 'Punk', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'punkrock', 'Punk Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'rap', 'Rap', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'rave', 'Rave', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'rb', 'R&B', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'retro', 'Retro', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'revival', 'Revival', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'rhythmicsoul', 'Rhythmic Soul', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'rockroll', 'Rock & Roll', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'salsa', 'Salsa', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'samba', 'Samba', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'satire', 'Satire', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'showtunes', 'Showtunes', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'ska', 'Ska', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'slowjam', 'Slow Jam', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'slowrock', 'Slow Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'sonata', 'Sonata', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'soul', 'Soul', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'soundclip', 'Sound Clip', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'southernrock', 'Southern Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'space', 'Space', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'speech', 'Speech', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'swing', 'Swing', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'symphonicrock', 'Symphonic Rock', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'symphony', 'Symphony', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'synthpop', 'Synthpop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'tango', 'Tango', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'techno', 'Techno', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'technoindustrial', 'Techno-Industrial', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'terror', 'Terror', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'thrashmetal', 'Thrash Metal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'top40', 'Top 40', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'trailer', 'Trailer', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'trance', 'Trance', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'tribal', 'Tribal', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'triphop', 'Trip-Hop', NULL, NULL);
INSERT INTO `s_attribute_type_lookup` VALUES ('MUSICGENRE', NULL, 'vocal', 'Vocal', NULL, NULL);
